#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

######################################
# Create container networks
######################################
- name: Create container networks
  ansible.builtin.import_playbook: hyperledger.fabricx.create_container_networks

######################################
# Crypto material with cryptogen
######################################
- name: Generate crypto material
  ansible.builtin.import_playbook: hyperledger.fabricx.artifacts.build_crypto_material

######################################
# Crypto material with Fabric CA
######################################
- name: Setup Fabric CA crypto material
  ansible.builtin.import_playbook: hyperledger.fabricx.fabric_ca_server.generate_crypto
  when:
    - "'fabric_cas' in groups"

- name: Transfer Fabric CA server configuration files
  ansible.builtin.import_playbook: hyperledger.fabricx.fabric_ca_server.configs
  when:
    - "'fabric_cas' in groups"

- name: Start Fabric CA servers
  ansible.builtin.import_playbook: hyperledger.fabricx.fabric_ca_server.start
  when:
    - "'fabric_cas' in groups"

- name: Init Fabric CA servers
  ansible.builtin.import_playbook: hyperledger.fabricx.fabric_ca_server.init
  when:
    - "'fabric_cas' in groups"

- name: Gather and register identities
  ansible.builtin.import_playbook: hyperledger.fabricx.fabric_ca_server.register_identities
  when:
    - "'fabric_cas' in groups"

- name: Generate Hyperledger Fabric-X Orderers crypto
  ansible.builtin.import_playbook: hyperledger.fabricx.orderer.generate_crypto

- name: Generate Hyperledger Fabric-X Committers crypto
  ansible.builtin.import_playbook: hyperledger.fabricx.committer.generate_crypto

- name: Generate Hyperledger Fabric-X Load generators crypto
  ansible.builtin.import_playbook: hyperledger.fabricx.loadgen.generate_crypto

- name: Generate Fabric-X EVM gateway crypto
  ansible.builtin.import_playbook: hyperledger.fabricx.evm_gateway.generate_crypto
  when:
    - "'evm_gateways' in groups"

- name: Generate Monitoring tools crypto
  ansible.builtin.import_playbook: hyperledger.fabricx.monitoring.generate_crypto
