#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Transfer Monitoring configuration files
  hosts: "{{ target_hosts | default('monitoring') }}:&monitoring"
  tasks:
    # =========================
    # Node Exporter
    # =========================
    - name: Transfer the Node Exporter configuration files
      ansible.builtin.include_role:
        name: hyperledger.fabricx.node_exporter
        tasks_from: config/transfer
      when:
        - node_exporter_port is defined
    # =========================
    # Postgres Exporter
    # =========================
    - name: Transfer the Postgres Exporter configuration files
      ansible.builtin.include_role:
        name: hyperledger.fabricx.postgres_exporter
        tasks_from: config/transfer
      when:
        - postgres_exporter_port is defined
    # =========================
    # Prometheus
    # =========================
    - name: Set Prometheus scrape services
      when:
        - prometheus_port is defined
      block:
        # =========================
        # HLFX Orderer metrics
        # =========================
        - name: Add Prometheus scrape services for Fabric-X Orderer
          vars:
            orderer_hosts: >-
              {{
                groups['fabric_x_orderers']
                | map('extract', hostvars)
                | selectattr('orderer_component_type', 'defined')
                | selectattr('organization.domain', 'defined')
                | selectattr('organization.domain', '==', current_orderer_organization_domain)
                | map(attribute='inventory_hostname')
                | list
              }}
          ansible.builtin.include_role:
            name: hyperledger.fabricx.orderer
            tasks_from: prometheus/get_scrapers
          loop: >-
            {{
              groups['fabric_x_orderers']
              | map('extract', hostvars)
              | selectattr('orderer_component_type', 'defined')
              | selectattr('organization.domain', 'defined')
              | map(attribute='organization.domain')
              | unique
              | list
            }}
          loop_control:
            loop_var: current_orderer_organization_domain
          when:
            - "'fabric_x_orderers' in groups"
            - orderer_hosts | length > 0
        # =========================
        # HLFX Committer metrics
        # =========================
        - name: Add Prometheus scrape services for Fabric-X Committer
          vars:
            committer_hosts: >-
              {{
                groups['fabric_x_committers']
                | map('extract', hostvars)
                | selectattr('committer_component_type', 'defined')
                | selectattr('organization.domain', 'defined')
                | selectattr('organization.domain', '==', current_committer_organization_domain)
                | map(attribute='inventory_hostname')
                | list
              }}
          ansible.builtin.include_role:
            name: hyperledger.fabricx.committer
            tasks_from: prometheus/get_scrapers
          loop: >-
            {{
              groups['fabric_x_committers']
              | map('extract', hostvars)
              | selectattr('committer_component_type', 'defined')
              | selectattr('organization.domain', 'defined')
              | map(attribute='organization.domain')
              | unique
              | list
            }}
          loop_control:
            loop_var: current_committer_organization_domain
          when:
            - "'fabric_x_committers' in groups"
            - committer_hosts | length > 0
        # =========================
        # HLFX Loadgen metrics
        # =========================
        - name: Add Prometheus scrape services for Fabric-X Loadgen
          vars:
            loadgen_hosts: >-
              {{
                groups['load_generators']
                | map('extract', hostvars)
                | selectattr('organization.domain', 'defined')
                | selectattr('organization.domain', '==', current_loadgen_organization_domain)
                | map(attribute='inventory_hostname')
                | list
              }}
          ansible.builtin.include_role:
            name: hyperledger.fabricx.loadgen
            tasks_from: prometheus/get_scrapers
          loop: >-
            {{
              groups['load_generators']
              | map('extract', hostvars)
              | selectattr('organization.domain', 'defined')
              | map(attribute='organization.domain')
              | unique
              | list
            }}
          loop_control:
            loop_var: current_loadgen_organization_domain
          when:
            - "'load_generators' in groups"
            - loadgen_hosts | length > 0
        # =========================
        # Yugabyte metrics
        # =========================
        - name: Add Prometheus scrape services for Yugabyte clusters
          vars:
            yugabyte_hosts: >-
              {{
                groups['all']
                | map('extract', hostvars)
                | selectattr('yugabyte_component_type', 'defined')
                | map(attribute='inventory_hostname')
                | list
              }}
          ansible.builtin.include_role:
            name: hyperledger.fabricx.yugabyte
            tasks_from: prometheus/get_scrapers
          when:
            - yugabyte_hosts | length > 0
        # =========================
        # Postgres Exporter metrics
        # =========================
        - name: Add Prometheus scrape services for Postgres Exporters
          vars:
            postgres_exporter_hosts: >-
              {{
                groups['all']
                | map('extract', hostvars)
                | selectattr('postgres_exporter_port', 'defined')
                | map(attribute='inventory_hostname')
                | list
              }}
          ansible.builtin.include_role:
            name: hyperledger.fabricx.postgres_exporter
            tasks_from: prometheus/get_scrapers
          when:
            - postgres_exporter_hosts | length > 0
        # =========================
        # Node Exporter metrics
        # =========================
        - name: Add Prometheus scrape services for Node Exporters
          vars:
            node_exporter_hosts: >-
              {{
                groups['all']
                | map('extract', hostvars)
                | selectattr('node_exporter_port', 'defined')
                | map(attribute='inventory_hostname')
                | list
              }}
          ansible.builtin.include_role:
            name: hyperledger.fabricx.node_exporter
            tasks_from: prometheus/get_scrapers
          when:
            - node_exporter_hosts | length > 0
        - name: Transfer the Prometheus configuration files
          vars:
            prometheus_scrape_services: >-
              {{
                (orderer_prometheus_scrape_services | default([]))
                + (committer_prometheus_scrape_services | default([]))
                + (loadgen_prometheus_scrape_services | default([]))
                + (yugabyte_prometheus_scrape_services | default([]))
                + (postgres_exporter_prometheus_scrape_services | default([]))
                + (node_exporter_prometheus_scrape_services | default([]))
              }}
          ansible.builtin.include_role:
            name: hyperledger.fabricx.prometheus
            tasks_from: config/transfer
    # =========================
    # Grafana
    # =========================
    - name: Transfer the Node Exporter Grafana Dashboard
      ansible.builtin.include_role:
        name: hyperledger.fabricx.node_exporter
        tasks_from: config/transfer_grafana_dashboard
      when:
        - grafana_web_port is defined
        - groups['all']
          | map('extract', hostvars)
          | selectattr('node_exporter_port', 'defined')
          | list
          | length > 0
    - name: Transfer the Fabric-X Committer Grafana Dashboard
      ansible.builtin.include_role:
        name: hyperledger.fabricx.committer
        tasks_from: config/transfer_grafana_dashboard
      when:
        - grafana_web_port is defined
        - groups['fabric_x_committers']
          | default([])
          | length > 0
    - name: Transfer the Fabric-X Orderer Grafana Dashboard
      ansible.builtin.include_role:
        name: hyperledger.fabricx.orderer
        tasks_from: config/transfer_grafana_dashboard
      when:
        - grafana_web_port is defined
        - groups['fabric_x_orderers']
          | default([])
          | length > 0
    - name: Transfer the Postgres Exporter Grafana Dashboard
      ansible.builtin.include_role:
        name: hyperledger.fabricx.postgres_exporter
        tasks_from: config/transfer_grafana_dashboard
      when:
        - grafana_web_port is defined
        - groups['all']
          | map('extract', hostvars)
          | selectattr('postgres_exporter_port', 'defined')
          | list
          | length > 0
    - name: Transfer the Yugabyte Grafana Dashboard
      ansible.builtin.include_role:
        name: hyperledger.fabricx.yugabyte
        tasks_from: config/transfer_grafana_dashboard
      when:
        - grafana_web_port is defined
        - groups['all']
          | map('extract', hostvars)
          | selectattr('yugabyte_component_type', 'defined')
          | list
          | length > 0
    - name: Transfer the Fabric-X EVM Loadgen Grafana Dashboard
      ansible.builtin.include_role:
        name: hyperledger.fabricx.evm_gateway
        tasks_from: config/transfer_grafana_dashboard
      when:
        - grafana_web_port is defined
        - groups['evm_gateways']
          | default([])
          | length > 0
    - name: Transfer the Grafana config files
      ansible.builtin.include_role:
        name: hyperledger.fabricx.grafana
        tasks_from: config/transfer
      when:
        - grafana_web_port is defined
    # =========================
    # Jaeger
    # =========================
    - name: Transfer the Jaeger config files
      ansible.builtin.include_role:
        name: hyperledger.fabricx.jaeger
        tasks_from: config/transfer
      when:
        - jaeger_collector_port is defined
