#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Teardown Fabric-X EVM gateway
  hosts: "{{ target_hosts | default('evm_gateways') }}:&evm_gateways"
  tasks:
    - name: Teardown Fabric-X EVM gateway
      ansible.builtin.include_role:
        name: hyperledger.fabricx.evm_gateway
        tasks_from: teardown
