#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch EVM gateway logs from container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.evm_gateway
    tasks_from: container/fetch_logs
  when: evm_gateway_use_container
